name: PlatformIO ESP32 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [esp32dev, esp32dev-no-ha]

    name: Build ${{ matrix.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Check PlatformIO installation
      run: pio --version

    - name: Create password.h for compilation
      run: |
        # Create a placeholder password.h file with default values for testing
        mkdir -p include
        cat > include/password.h << 'EOF'
        #ifndef PASSWORD_H
        #define PASSWORD_H
        
        const char *WIFI_SSID = "TestSSID";
        const char *WIFI_PASS = "TestPassword";
        
        // Home Assistant credentials
        const char *HA_IP = "homeassistant.local";
        const uint16_t HA_PORT = 8123;
        const char *HA_ACCESS_TOKEN = "test_token";
        
        #endif
        EOF

    - name: Install dependencies
      run: pio pkg install
    
    - name: Build environment ${{ matrix.environment }}
      run: pio run -e ${{ matrix.environment }}
      
    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.environment }}
        path: .pio/build/${{ matrix.environment }}/firmware.bin
        if-no-files-found: error