name: PlatformIO ESP32 Build

on:
  push:
    branches: [ gitaction-compilation-check ]
  pull_request:
    branches: [ gitaction-compilation-check ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-config:
          # Default build with Home Assistant enabled
          - name: "Standard Build (HA Enabled)"
            flags: ""
          # Build with Home Assistant disabled
          - name: "No Home Assistant"
            flags: "-DHAL_DISABLE_HOME_ASSISTANT"
          # Additional builds can be added here

    name: ${{ matrix.build-config.name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Check PlatformIO installation
      run: pio --version

    - name: Create password.h for compilation
      run: |
        # Create a placeholder password.h file with default values for testing
        mkdir -p include
        cat > include/password.h << 'EOF'
        #ifndef PASSWORD_H
        #define PASSWORD_H
        
        const char *WIFI_SSID = "TestSSID";
        const char *WIFI_PASS = "TestPassword";
        
        // Home Assistant credentials
        const char *HA_IP = "homeassistant.local";
        const uint16_t HA_PORT = 8123;
        const char *HA_ACCESS_TOKEN = "test_token";
        
        #endif
        EOF

    - name: Install dependencies
      run: pio pkg install
    
    - name: Build project with ${{ matrix.build-config.name }}
      run: pio run -e esp32dev ${{ matrix.build-config.flags }}
      
    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ github.run_number }}-${{ github.job }}-${{ matrix.build-config.name }}
        path: .pio/build/esp32dev/firmware.bin
        if-no-files-found: error